# Generated by Django 6.0.1 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='blog_files/'),
        ),
    ]
