# Generated by Django 6.0.1 on 2026-03-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reverse_mobile_messages',
            field=models.BooleanField(default=False),
        ),
    ]
